49 프로필, 비밀번호 변경 페이지 완성
Tra-Book/Frontend pull request #50
Opened 2024-09-08 08:42 UTC by sjg729729

### 기능
1. 프로필 수정 - 닉네임, 상태 메시지, 프로필 이미지
2. 비밀번호 변경

### 수정 사항
1. 사이드 바 - 이메일 로그인일 때만 '비밀변호 변경' 항목이 보입니다.
<img width="180" alt="스크린샷 2024-09-08 오후 5 39 41" src="https://github.com/user-attachments/assets/1ede0eab-4269-47af-80c9-8815b6a9e3fc">

2. 모바일 메뉴 - 'MY' 밑에 프로필 변경이 추가되었습니다. 이메일 로그인일 때만 '비밀변호 변경'항목이 보입니다.
<img width="197" alt="스크린샷 2024-09-08 오후 5 31 35" src="https://github.com/user-attachments/assets/0ceb3196-6fd0-49f5-8ef7-4b35970da102">

### Session
image(프로필 사진 url), profile_message(상태 메세지), provider(로그인 방식)이 추가되었습니다.
provider를 추가해서 credentials(이메일) 로그인 일때만 '비밀번호 변경'항목이 보이도록 하였습니다.
type을 아직 설정해두지 않아서 any 타입을 사용하였습니다.

### 추가되어야할 기능
1. 비밀번호 찾기
2. 프로필 이미지 삭제(초기화)

2024-09-08 09:53 UTC, jihostudy requested changes
사용하신 `console.log()`는 삭제해주시면 감사하겠습니다~

2024-09-08 13:10 UTC, jihostudy commented on lib/types/Session.ts
> +  provider: string
provider는 "credentials" | "kakao" | "google" | "naver"로 설정할 수 있지 않을까요?

2024-09-08 13:41 UTC, jihostudy commented on components/main/ProfileChange.tsx
> +          update({ nickname: nickname, status_message: message, image: data.profilePhoto })
변경이 완료되었으면, session 값을 업데이트 하고 업데이트 된 값이 reloading되면서 반영이 안되는것 같습니다.

2024-09-08 13:44 UTC, jihostudy commented on components/main/ProfileChange.tsx
> +      alert('닉네임은 영문자, 한글, 숫자만 사용 가능합니다.')
이렇게 설정한 이유가 있을까요? (띄어쓰기, * 제외하곤 괜찮을 것 같기도 한데욤)
* : SQL Injection 방지

2024-09-08 14:02 UTC, jihostudy commented
## 요청사항
1. 유저 정보에 따라 `Sidebar`의 이미지와 이름, 상태메세지 변경부탁드립니다.

2024-09-08 14:03 UTC, jihostudy commented on app/(route)/(header)/main/password/page.tsx
> +        <Link href={ROUTES.AUTH.SIGNOUT.url} className='mx-5 text-black underline hover:cursor-pointer'>
hover: `text-tbBlue` 부탁드릴게요!

2024-09-08 14:12 UTC, sjg729729 commented on app/(route)/(header)/main/password/page.tsx
> +        <Link href={ROUTES.AUTH.SIGNOUT.url} className='mx-5 text-black underline hover:cursor-pointer'>
탈퇴 잘 안보이게 하려고 추가 안했는데 할까요??ㅋㅋㅋ

2024-09-09 09:32 UTC, sjg729729 commented on components/main/ProfileChange.tsx
> +      alert('닉네임은 영문자, 한글, 숫자만 사용 가능합니다.')
게임 닉네임 형식 참고해서 임의로 설정한겁니다!!
추후에 확실하게 형식 정해야할 것 같아요

2024-09-09 16:24 UTC, jihostudy approved these changes
LGTM 고생많으셨습니다~ 머지해주세요

2024-09-10 04:59 UTC, merged